const TermsConditions = {
    heading: "Website Terms and Conditions",
    subHeading1: "Introduction",
    para11: "Your use of our website is subject to these terms of use, and by using our website, you fully accept these terms of use. You must not use our website if you disagree with these terms of use or any part of them.",
    para12: "Use of our website requires that you be a student at Coventry University. You indicate and warrant that you are a Coventry University student by using our website and agreeing to these terms of use.",
    subHeading2: "Website usage license",
    para21: "We are the exclusive owners of the intellectual property rights of the website and the content on it, unless otherwise noted. All of these intellectual property rights are reserved, subject to the licence below.",
    para22: "In accordance with the limitations outlined below and elsewhere in these terms of use, you may read, download for temporary storage only, and print pages from the website for your own personal use.",
    filler1: "You must not:",
    point1: "republish material from this website (including republication on another website);",
    point2: "sell, rent or sub-license material from the website;",
    point3: "reproduce, duplicate, copy or otherwise exploit material on our website for a commercial purpose;",
    point4: "edit or otherwise modify any material on the website; or",
    point5: "redistribute material from this website [except for content specifically and expressly made available for redistribution]",
    subHeading3: "Acceptable use",
    para31: "You are not permitted to use our website in any way that endangers it or that could endanger its availability or accessibility. You are also not permitted to use it for any purposes or activities that are prohibited, illegal, fraudulent, or harmful.",
    para32: "You are prohibited from using our website to copy, store, host, transmit, send, utilise, publish, or distribute any content that could expose users to spyware, computer viruses, Trojan horses, worms, keystroke loggers, rootkits, or other harmful software.",
    para33: "Without our prior written authorization, you may not engage in any systematic or automated data collection activities on or related to our website (including, but not limited to, scraping, data mining, data extraction, and data harvesting).",
    para34: "You must not use our website for transmitting unsolicited commercial communications.",
    para35: "Without our prior written consent, you are not permitted to use our website for any marketing-related reasons.",
    subHeading4: "Limited access",
    para41: "Our website has some places that are limited in access. At our discretion, we have the right to restrict access to other parts of our website or even the entire website.",
    para42: "You are responsible for keeping the password secure if we give it to you or if you create a user ID and password to give you access to restricted parts of our website or other material or services.",
    para43: "If you become aware of any unauthorised use of your account or password, you must immediately notify us in writing.",
    para44: "Any action on our website that results from your failure to keep your password private is your responsibility, and you could be held accountable for any losses as a result.",
    para45: "To access our website, you may not use anyone else's user ID or password.",
    subHeading5: "User consent",
    para51: 'In these terms of use, "your content" refers to any anything that you submit to our website, for any reason, including text, photos, audio, video, and audio-visual information.',
    para52: "You give us a perpetual, non-exclusive, worldwide licence to use, copy, modify, publish, translate, and distribute your content in any form, in our website. Additionally, you give us the authority to sue for infringement of these rights and to sublicense these rights.",
    para53: "Any content that is currently or has ever been the subject of legal action, pending litigation, or another comparable complaint may not be submitted to the website.",
    para54: "Any content contributed to, stored on, hosted, or published on our website may be edited or removed at our discretion.",
    para55: "Despite the fact that we have rights to your content under these terms of use, we will use your data only to ensure if the website presents content effectively, authenticate you at the time of registration and to notify you in case of changes in our terms and conditions.",
    subHeading6: "Limited warranties",
    para61: "We make no promises regarding the accuracy or completeness of the data on this website, and we don't guarantee that it will always be accessible or that it will be kept up to date.",
    para62: "To the fullest extent permitted by applicable law, we hereby disclaim all representations, warranties, and conditions with respect to this website and the use thereof, including, without limitation, all implied warranties of satisfactory quality, merchantability, and/or fitness for a particular purpose.",
    para63: "The full name of our company is Tag-along."
};

export default TermsConditions;
